version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "scdip"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fcvajeue9xxx"
s3_prefix = "scdip"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

