AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Simple Rekommend web service for retrieving questions and resources
Parameters:
  Stage:
    Type: String
    Default: dev
Resources:
  RekommendApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      Cors:
        AllowMethods: "'GET,POST,DELETE,OPTIONS'"
        AllowHeaders: "'authorization'"
        AllowOrigin: "'*'"
      OpenApiVersion: '2.0'

  RekommendGetItems:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.getitems
      Runtime: nodejs12.x
      CodeUri: src/
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref Table
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Events:
        GetItems:
          Type: Api
          Properties:
            RestApiId: !Ref RekommendApi
            Path: /test/{testId}
            Method: get

  RekommendGetResources:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.getresources
      Runtime: nodejs12.x
      CodeUri: src/
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref Table
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Events:
        GetResources:
          Type: Api
          Properties:
            RestApiId: !Ref RekommendApi
            Path: /resources/{testId}
            Method: get

  Table:
    Type: AWS::Serverless::SimpleTable
    TableName: !Join [ "", [ !Ref Stage, "-rekommend"]]

Outputs:
  ApiURL:
    Description: "API endpoint URL"
    Value: !Sub "https://${RekommendApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"